[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-app"
version = "0.1.0"
description = "MCP Development Environment"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
dev-dependencies = []
